### PR TITLE
Fix menu rendering placement

### LINKED ISSUE #447: Submenu occasionally renders in the wrong place
**Checklist:**

- [x] I updated to the latest version available (actually I built the latest from source)
- [x] I cleared the cache of my browser

**Release with the issue:**
master

**Last working release (if known):**
Not sure if this behavior happened on v3.0.0-rc.1 or not.

**Browser and Operating System:**

Android Companion app latest beta version.

**Description of problem:**

https://user-images.githubusercontent.com/29582865/156897346-21b1aacb-d72c-4299-86e5-622c8e79409d.mp4

**Additional information:**

I didn't know what to put in the title...

### PR DESCRIPTION
**Pull request by dermotduffy**
* Closes #447

### CODE REVIEW

**Comment by dermotduffy** [comment]
@felipecrs Would you mind testing this out on your end and see if it fixes your menu location problem?

**Comment by felipecrs** [comment]
One sec.

**Comment by felipecrs** [comment]
Sweet!

https://user-images.githubusercontent.com/29582865/158074269-149ef967-7f89-46eb-a2ba-bdc6e08cfb58.mp4

**Comment by dermotduffy** [comment]
Thank you for the instant test @felipecrs !

**Pull request merged**
