### PR TITLE
Use http thumbnails

### PR DESCRIPTION
**Pull request by uvjustin**
@dermotduffy This seems to work, maybe you can test it out on your end.

### CODE REVIEW

**Comment by dermotduffy** [comment]
Oh oh, bad timing -- I also worked on this, see https://github.com/dermotduffy/frigate-hass-card/pull/779 .

Your solution is much simpler (do the re-signing in one go at the start), my solution pushes the signing down to the thumbnail component so the thumbnails individually "load".

**Comment by uvjustin** [comment]
Oh I see, haha.
Actually, after doing this (my way at least, haven't looked at yours yet) I noticed there is a lot of wasted effort with the signing. Maybe it would be better to just have the integration endpoint just sign the paths when the BrowseMediaSource is returned the first time.
But as you mentioned, doing it either this way or pre-signing has the issue of expiration time. One hack would just be to set a longer expiry on the signing, like a day or something. Another way would be to actually go down and fetch the URLs similar to how I'm doing it here and then just embedding the result in the thumbnails as base64 strings (i.e. the way they're stored now).

**Comment by dermotduffy** [comment]
> Actually, after doing this (my way at least, haven't looked at yours yet) I noticed there is a lot of wasted effort with the signing. Maybe it would be better to just have the integration endpoint just sign the paths when the BrowseMediaSource is returned the first time.
> But as you mentioned, doing it either this way or pre-signing has the issue of expiration time. One hack would just be to set a longer expiry on the signing, like a day or something. 

A common use case for the card is long running dashboards (e.g. wall-mounted-tablet / Nest hub devices, etc), so that would probably not work sadly unless we picked a really long signature time (e.g. a month). This [irritating] HA auth scheme is a pretty sore point -- I've had probably 10+ user bugs filed on rejected requests when an old token is used accidentally and something doesn't load properly (also resulting in ip bans -- but from that other bugs it looks like that may no longer be an issue in the August HA release).

**Comment by uvjustin** [comment]
I see you ended up merging the other PR, so I'll close this one.
I did update the PR to embed the image (similar to the base64 idea above) using a blob. I'll push that commit so we can have it here as an alternative (the performance might be better as the assets are preloaded).

**Comment by dermotduffy** [comment]
Thanks @uvjustin . The embedding is another good idea to get around the expiration issue at a cost of fetching all the thumbnails in advance -- might be a good plan is the latency ends up hurting too much.

**Pull request closed without merging**
