### PR TITLE
feat: Add new `casting` profile

### PR DESCRIPTION
**Pull request by dermotduffy**

### CODE REVIEW

**Comment by felipecrs** [comment]
The profile works great by the way, except that I could not make it work under my TV.

It has been some time since I don't actually perform casting.

It just stays like this forever:

https://github.com/user-attachments/assets/1dd3b82f-c90b-46fb-be53-3bc55e0b0186

Here's the configuration I'm using:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.video_porteiro
    live_provider: go2rtc
    image:
      refresh_seconds: 1
profiles:
  - low-performance
  - casting
live:
  controls:
    builtin: false
  show_image_during_load: true
image:
  refresh_seconds: 1
```

By the way, I'm not sure which `image.refresh_seconds` is actually effective for the `show_image_during_load`. That's why I have both.

I wonder if you can reproduce it.

**Comment by dermotduffy** [comment]
> By the way, I'm not sure which image.refresh_seconds is actually effective for the show_image_during_load. That's why I have both.

The one under `camera` should be it, since that is the configuration for the "live provider".

Let me try to cast (also been a while since I did it!).

**Comment by felipecrs** [comment]
I can reproduce that behavior in my older Sony TV with Android TV 9. It doesn't get past the Connected HA screen.

However, in my two Chromecast with Google TV with Android 12 devices, they get past that screen and behaves as the video above.

Regardless, something seems wrong beyond the card itself.

**Comment by felipecrs** [comment]
I don't think it's worth keeping this PR unmerged anyway. The only feedback I have would be if these settings be included in the profile or not:

1. `live.controls.builtin: false`
2. `live.show_image_during_load: true`
3. Perhaps `cameras_global.image.refresh_seconds: 1`?

**Pull request merged**
