### PR TITLE
Deal with camera unavailability in a cleaner way

### LINKED ISSUE #1273: Camera unavailable should not print configuration
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

Latest

**Last working release (if known):**

If I remember well this was not always like that.

**Browser and Operating System:**

N/A

**Description of problem:**

When my camera becomes unavailable for whatever reason (like bad Wi-Fi for example), the card should only show that the camera is unavailable and not print the entire configuration.

This is an error that is expected to happen, and not something that would require fixing the configuration.

image

**Frigate card diagnostic information**

N/A

**Javascript errors shown in the web inspector (if applicable):**

N/A

**Additional information:**

Déjà vu? No:

- https://github.com/dermotduffy/frigate-hass-card/issues/759

Also, this is especially worse now that the Frigate integration itself reports unavailability:

- https://github.com/blakeblackshear/frigate-hass-integration/issues/406

### PR DESCRIPTION
**Pull request by dermotduffy**
* Closes #1273

### CODE REVIEW

**Comment by tchris227** [comment]
I'm very much looking forward to this fix.  Any idea on when it will make it into a release?

**Comment by nibagit** [comment]
Any update on this?

**Comment by Lockie85** [comment]
Yes, this please. Any updates on this?

**Comment by dermotduffy** [comment]
Sorry, no particular updates beyond "this is already fixed on the dev branch". You are welcome to try it out (no support is offered on unreleased code, though):

https://card.camera/#/advanced-installation?id=unreleased-versions

**Pull request merged**
