### PR TITLE
Add `inlang` to make the contribution of translations easier

### PR DESCRIPTION
**Pull request by NiklasBuchfink**
Added as suggested in https://github.com/blakeblackshear/frigate-hass-integration/pull/478#issuecomment-1518792669

### Description
This pull request adds the possibility for contributors and translators to manage translations in a UI instead of files with no overhead for the maintainers.

To get a UI for translations contained in this repository, an [inlang.config.js](https://inlang.com/documentation/config) has been created at the root of the repository.
**Note:** This link should be changed to point to _dermotduffy_ instead of _NiklasBuchfink_ after this PR has been merged.

### Preview
The changes of this PR and a live instance of the editor can be previewed with the following link https://inlang.com/editor/github.com/NiklasBuchfink/frigate-hass-card.

### Limitations
**Certain actions are slow**
inlang is running entirely on git, giving tremendous CI/CD and contribution power to localization. That means that the whole frigate-hass-card repo is cloned into the browser which makes certain actions like the initial load and pushing changes slow. Those limitations will be fixed with future releases and require no input from frigate-hass-card.

### CODE REVIEW

**Comment by NiklasBuchfink** [comment]
@dermotduffy At the moment there are 26 translations missing for `it` and `pt-BR` and unfortunately I don`t speak any of the languages. But I could still add a machine translation for the missing strings via the editor if you want.

I added the information above because it may be useful if someone comes back to this PR at a later date.

**Comment by dermotduffy** [comment]
@NiklasBuchfink -- there are other contributors that occasionally provide other translations, and the code falls back to English when a translation is not available. The sense I got from them was that this was preferred than relying on machine translation, hence I avoided providing machine translations when I added those strings. So, in short: don't worry about it! (But German obviously very welcome if you speak it natively).

**Comment by dermotduffy** [comment]
Oh, would you mind putting it into the `dev` branch?

**Comment by NiklasBuchfink** [comment]
@dermotduffy I understand, that makes sense.
Translating the 342 strings in German would definitely take a bit more time. I hope it's ok if I don't do it immediately.

**Comment by dermotduffy** [comment]
Thanks @NiklasBuchfink . No worries I know it's not a trivial exercise, appreciate the consideration & contribution!

**Pull request merged**
