### PR TITLE
Update various npm dependencies

### PR DESCRIPTION
**Pull request by felipecrs**
This will auto close the Dependabot PRs once it gets merged with the main branch.

I'm testing this, and so far, it's okay.

This also fixes the following warning:

```log
[3/4] Linking dependencies...
warning "rollup-plugin-typescript2 > @yarn-tool/resolve-package > upath2@3.1.12" has unmet peer dependency "@types/node@*".
```

- Refs https://github.com/ezolenko/rollup-plugin-typescript2/pull/324
- Refs https://github.com/bluelovers/ws-iconv/issues/5

### List of dependencies

```
@cycjimmy/jsmpeg-player                   ^5.1.1  →    ^6.0.2
@lit-labs/task                            ^1.1.1  →    ^1.1.2
@material/mwc-menu                       ^0.25.3  →   ^0.26.1
@material/rtl                            ^13.0.0  →   ^14.0.0
embla-carousel-wheel-gestures             ^2.1.1  →    ^2.2.0
home-assistant-js-websocket               ^6.1.1  →    ^7.0.3
lit                                       ^2.2.1  →    ^2.2.3
moment                                   ^2.29.2  →   ^2.29.3
quick-lru                                 ^6.1.0  →    ^6.1.1
vis-data                                  ^7.1.3  →    ^7.1.4
vis-util                                  ^5.0.2  →    ^5.0.3
xss                                      ^1.0.10  →   ^1.0.11
zod                                      ^3.13.4  →   ^3.16.0
side-drawer                               ^3.0.0  →    ^3.1.0
@babel/core                              ^7.17.7  →  ^7.17.10
@babel/plugin-proposal-class-properties  ^7.14.5  →   ^7.16.7
@babel/plugin-proposal-decorators        ^7.15.8  →   ^7.17.9
@rollup/plugin-commonjs                  ^21.0.2  →   ^22.0.0
@rollup/plugin-node-resolve              ^13.1.3  →   ^13.3.0
@types/lodash-es                         ^4.17.5  →   ^4.17.6
@typescript-eslint/eslint-plugin         ^5.15.0  →   ^5.23.0
@typescript-eslint/parser                ^5.15.0  →   ^5.23.0
eslint                                   ^8.11.0  →   ^8.15.0
eslint-plugin-import                     ^2.25.4  →   ^2.26.0
npm-check-updates                        ^12.5.3  →   ^13.0.0
prettier                                  ^2.6.0  →    ^2.6.2
rollup                                   ^2.72.1  →   ^2.73.0
sass                                     ^1.49.9  →   ^1.51.0
typescript                                ^4.6.2  →    ^4.6.4
```

### References

- https://github.com/cycjimmy/jsmpeg-player/releases
- https://github.com/home-assistant/home-assistant-js-websocket/releases
- https://github.com/rollup/plugins/blob/master/packages/commonjs/CHANGELOG.md#v2200

### CODE REVIEW

**Comment by dermotduffy** [comment]
FYI I did a mass dep update in https://github.com/dermotduffy/frigate-hass-card/pull/637 , so we probably don't need this anymore?

**Comment by felipecrs** [comment]
Actually you are missing a few:

```console
$ yarn outdated
yarn outdated v1.22.18
info Color legend : 
 "<red>"    : Major Update backward-incompatible updates 
 "<yellow>" : Minor Update backward-compatible features 
 "<green>"  : Patch Update backward-compatible bug fixes
Package                     Current Wanted  Latest Package Type    URL                                                                    
@cycjimmy/jsmpeg-player     5.1.1   5.1.1   6.0.2  dependencies    https://github.com/cycjimmy/jsmpeg-player#readme                       
@material/mwc-menu          0.25.3  0.25.3  0.26.1 dependencies    https://github.com/material-components/material-web#readme             
@material/rtl               13.0.0  13.0.0  14.0.0 dependencies    https://github.com/material-components/material-components-web#readme  
@rollup/plugin-commonjs     21.1.0  21.1.0  22.0.0 devDependencies https://github.com/rollup/plugins/tree/master/packages/commonjs/#readme
home-assistant-js-websocket 6.1.1   6.1.1   7.1.0  dependencies    https://github.com/home-assistant/home-assistant-js-websocket#readme   
npm-check-updates           12.5.12 12.5.12 13.1.1 devDependencies https://github.com/raineorshine/npm-check-updates                      
rollup-plugin-typescript2   0.31.2  0.31.2  0.32.1 devDependencies https://github.com/ezolenko/rollup-plugin-typescript2                  
Done in 6.63s.
```

With colors:

image

**Comment by felipecrs** [comment]
I rebased the PR, it was produced this way:

```console
$ npx ncu -u # if you don't plan to use npm-check-updates, you may remove it from devDeps so

$ yarn install
```

And, effectively, it upgrades the following packages:

image

**Comment by dermotduffy** [comment]
Thanks @felipecrs . I think it may be time for me to move away from the keyboard for today ;-) (I was missing --latest on `yarn upgrade`). Fixed in #639 .

**Comment by felipecrs** [comment]
Hahaha, all good. Thank you a lot!

**Pull request closed without merging**
