### PR TITLE
Fix iOS date picker

### PR DESCRIPTION
**Pull request by kirsch33**
resolves https://github.com/dermotduffy/frigate-hass-card/issues/1289

not sure if this has other implications, but I compiled and ran it on my device and it seems to work fine.

### CODE REVIEW

**Comment by dermotduffy** [comment]
From the [option docs](https://flatpickr.js.org/mobile-support/) that seems like it would (on Android) cause it to not use the nicer/native date picker, so I'm not sure this is a good idea as is. I would guess if this works there's an upstream issue in the date picker for iOS itself.

**Comment by kirsch33** [comment]
I think you're right as this issue indicates https://github.com/flatpickr/flatpickr/issues/1928

However that issue has been open since 2019 so I don't expect it to ever be resolved.

**Comment by dermotduffy** [comment]
> However that issue has been open since 2019 so I don't expect it to ever be resolved.

Agreed. A simple hack might be to disable only on iOS devices, and allow otherwise. A (much) larger fix might be to change the date picker library entirely.

**Comment by kirsch33** [comment]
I'll see what I can to do make it iOS specific. I'm not a developer by trade, just dabble a bit but that doesn't sound too hard to accomplish!

**Comment by dermotduffy** [comment]
Decided to fix this a different way in https://github.com/dermotduffy/frigate-hass-card/pull/1364 as I don't like the idea of relying on an unmaintained library , so I'm going to close this for now. Thank you for your help!

**Pull request closed without merging**
