### PR TITLE
Move all live provider options into cameras

### PR DESCRIPTION
**Pull request by dermotduffy**
Simplify the configuration by removing all live provider options under the `live:` YAML stanza. Instead live providers can only be configured in the relevant camera entry. For most users, this should not be a real change. An automated upgrade will correct the configuration for many of those that remain, however advanced configurations using overrides may no longer work / be possible (specifically: `cameras:` configuration is not overrideable, whereas the `live:` configuration is -- so no substitute in functionality is possible in these cases).

**Before:**

```yaml
live:
  webrtc_card:
    ui: true
  image:
    refresh_seconds: 5
  jsmpeg:
    options:
      audioBufferSize: 0
```

**After:**
```yaml
cameras:
[...]
  - webrtc_card:
      ui: true
    image:
      refresh_seconds: 5
    jsmpeg:
      options:
        audioBufferSize: 0
```

Advantages:
 - More intuitive behavior.
 - Keeps camera configuration hermetic (at least one subtle bug is fixed by this)

Disadvantages:
 - Possibly more verbose configuration for multi-camera setups.
 - Slightly reduced override functionality.

Closes:
  - #922

### CODE REVIEW

**Comment by felipecrs** [comment]
@dermotduffy just to be clear, it also means that I'll have to copy all my WebRTC global settings to each of my camera, right?

It would be nice if there was still a way to set global options so that I don't have to duplicate these several times, but it's ok if that's not the case.

(BTW, the automatic upgrade simply wiped my global webrtc settings without copying them to the cameras).

**Comment by felipecrs** [comment]
Before auto migration:

```yaml
type: custom:frigate-card
view:
  default: live
  update_force: false
overrides:
  - conditions:
      fullscreen: true
    overrides:
      menu:
        style: overlay
      live:
        layout:
          fit: contain
          position:
            x: 50
            'y': 50
menu:
  buttons:
    frigate:
      enabled: false
    snapshots:
      enabled: false
    image:
      enabled: false
    cameras:
      alignment: opposing
    timeline:
      enabled: false
    media_player:
      enabled: true
    clips:
      enabled: true
    camera_ui:
      enabled: true
    substreams:
      icon: mdi:high-definition
      priority: 40
  style: outside
  position: top
  alignment: left
live:
  preload: false
  controls:
    next_previous:
      style: none
    title:
      mode: none
    thumbnails:
      mode: none
  lazy_load: true
  lazy_unload: all
  show_image_during_load: false
  layout:
    fit: cover
    position:
      x: 0
      'y': 0
  image:
    refresh_seconds: 1
  webrtc_card:
    muted: true
    ui: true
    mode: webrtc
    style: |
      video {aspect-ratio: 16/9; object-fit: cover; object-position: left top;}
      .mode {display: none}
      .fullscreen {display: none}
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
elements:
  - type: custom:frigate-card-conditional
    conditions:
      view:
        - live
      camera:
        - camera.rua
      media_loaded: false
    elements:
      - type: custom:frigate-card-ptz
        orientation: vertical
        service: onvif.ptz
        style:
          transform: none
          right: 5%
          top: 45%
        data_up:
          entity_id: camera.rua_onvif
          tilt: UP
          move_mode: ContinuousMove
          speed: 0.05
          continuous_duration: 0.05
        data_down:
          entity_id: camera.rua_onvif
          tilt: DOWN
          move_mode: ContinuousMove
          speed: 0.05
          continuous_duration: 0.05
        data_left:
          entity_id: camera.rua_onvif
          pan: LEFT
          move_mode: ContinuousMove
          speed: 0.05
          continuous_duration: 0.05
        data_right:
          entity_id: camera.rua_onvif
          pan: RIGHT
          move_mode: ContinuousMove
          speed: 0.05
          continuous_duration: 0.05
  - type: custom:frigate-card-conditional
    conditions:
      view:
        - live
      camera:
        - camera.rua
    elements:
      - type: custom:frigate-card-menu-submenu-select
        entity: select.camera_da_rua_night_vision
        options:
          '0':
            icon: mdi:theme-light-dark
          '1':
            icon: mdi:weather-sunny
          '2':
            icon: mdi:weather-night
cameras:
  - camera_entity: camera.video_porteiro
    live_provider: webrtc-card
    webrtc_card:
      url: video_porteiro
    dependencies:
      cameras:
        - video_porteiro_hd
  - camera_entity: camera.rua
    live_provider: webrtc-card
    webrtc_card:
      url: rua
    dependencies:
      cameras:
        - rua_hd
  - camera_entity: camera.morro
    live_provider: webrtc-card
    webrtc_card:
      url: morro
    dependencies:
      cameras:
        - morro_hd
  - camera_entity: camera.portao
    live_provider: webrtc-card
    webrtc_card:
      url: portao
  - camera_entity: camera.video_porteiro
    live_provider: webrtc-card
    title: Vídeo Porteiro (HD)
    id: video_porteiro_hd
    webrtc_card:
      url: video_porteiro_hd
    hide: true
  - camera_entity: camera.rua
    live_provider: webrtc-card
    title: Rua (HD)
    id: rua_hd
    webrtc_card:
      url: rua_hd
    hide: true
  - camera_entity: camera.morro
    live_provider: webrtc-card
    title: Morro (HD)
    id: morro_hd
    webrtc_card:
      url: morro_hd
    hide: true
  - camera_entity: camera.portao
    live_provider: webrtc-card
    title: Portão (HD)
    id: portao_hd
    webrtc_card:
      url: portao_hd
    hide: true
    dependencies:
      cameras:
        - camera.portao
image:
  mode: camera
performance:
  profile: low
  features:
    animated_progress_indicator: false
  style:
    box_shadow: false
    border_radius: false
media_viewer:
  auto_play: all
  auto_unmute: all
```

After auto-migration:

```yaml
type: custom:frigate-card
view:
  default: live
  update_force: false
overrides:
  - conditions:
      fullscreen: true
    overrides:
      menu:
        style: overlay
      live:
        layout:
          fit: contain
          position:
            x: 50
            'y': 50
menu:
  buttons:
    frigate:
      enabled: false
    snapshots:
      enabled: false
    image:
      enabled: false
    cameras:
      alignment: opposing
    timeline:
      enabled: false
    media_player:
      enabled: true
    clips:
      enabled: true
    camera_ui:
      enabled: true
    substreams:
      icon: mdi:high-definition
      priority: 40
  style: outside
  position: top
  alignment: left
live:
  preload: false
  controls:
    next_previous:
      style: none
    title:
      mode: none
    thumbnails:
      mode: none
  lazy_load: true
  lazy_unload: all
  show_image_during_load: false
  layout:
    fit: cover
    position:
      x: 0
      'y': 0
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
elements:
  - type: custom:frigate-card-conditional
    conditions:
      view:
        - live
      camera:
        - camera.rua
      media_loaded: false
    elements:
      - type: custom:frigate-card-ptz
        orientation: vertical
        service: onvif.ptz
        style:
          transform: none
          right: 5%
          top: 45%
        data_up:
          entity_id: camera.rua_onvif
          tilt: UP
          move_mode: ContinuousMove
          speed: 0.05
          continuous_duration: 0.05
        data_down:
          entity_id: camera.rua_onvif
          tilt: DOWN
          move_mode: ContinuousMove
          speed: 0.05
          continuous_duration: 0.05
        data_left:
          entity_id: camera.rua_onvif
          pan: LEFT
          move_mode: ContinuousMove
          speed: 0.05
          continuous_duration: 0.05
        data_right:
          entity_id: camera.rua_onvif
          pan: RIGHT
          move_mode: ContinuousMove
          speed: 0.05
          continuous_duration: 0.05
  - type: custom:frigate-card-conditional
    conditions:
      view:
        - live
      camera:
        - camera.rua
    elements:
      - type: custom:frigate-card-menu-submenu-select
        entity: select.camera_da_rua_night_vision
        options:
          '0':
            icon: mdi:theme-light-dark
          '1':
            icon: mdi:weather-sunny
          '2':
            icon: mdi:weather-night
cameras:
  - camera_entity: camera.video_porteiro
    live_provider: webrtc-card
    webrtc_card:
      url: video_porteiro
    dependencies:
      cameras:
        - video_porteiro_hd
  - camera_entity: camera.rua
    live_provider: webrtc-card
    webrtc_card:
      url: rua
    dependencies:
      cameras:
        - rua_hd
  - camera_entity: camera.morro
    live_provider: webrtc-card
    webrtc_card:
      url: morro
    dependencies:
      cameras:
        - morro_hd
  - camera_entity: camera.portao
    live_provider: webrtc-card
    webrtc_card:
      url: portao
  - camera_entity: camera.video_porteiro
    live_provider: webrtc-card
    title: Vídeo Porteiro (HD)
    id: video_porteiro_hd
    webrtc_card:
      url: video_porteiro_hd
    hide: true
  - camera_entity: camera.rua
    live_provider: webrtc-card
    title: Rua (HD)
    id: rua_hd
    webrtc_card:
      url: rua_hd
    hide: true
  - camera_entity: camera.morro
    live_provider: webrtc-card
    title: Morro (HD)
    id: morro_hd
    webrtc_card:
      url: morro_hd
    hide: true
  - camera_entity: camera.portao
    live_provider: webrtc-card
    title: Portão (HD)
    id: portao_hd
    webrtc_card:
      url: portao_hd
    hide: true
    dependencies:
      cameras:
        - camera.portao
image:
  mode: camera
performance:
  profile: low
  features:
    animated_progress_indicator: false
  style:
    box_shadow: false
    border_radius: false
media_viewer:
  auto_play: all
  auto_unmute: all
```

Fixed manually:

```yaml
type: custom:frigate-card
view:
  default: live
  update_force: false
overrides:
  - conditions:
      fullscreen: true
    overrides:
      menu:
        style: overlay
      live:
        layout:
          fit: contain
          position:
            x: 50
            'y': 50
menu:
  buttons:
    frigate:
      enabled: false
    snapshots:
      enabled: false
    image:
      enabled: false
    cameras:
      alignment: opposing
    timeline:
      enabled: false
    media_player:
      enabled: true
    clips:
      enabled: true
    camera_ui:
      enabled: true
    substreams:
      icon: mdi:high-definition
      priority: 40
  style: outside
  position: top
  alignment: left
live:
  preload: false
  controls:
    next_previous:
      style: none
    title:
      mode: none
    thumbnails:
      mode: none
  lazy_load: true
  lazy_unload: all
  show_image_during_load: false
  layout:
    fit: cover
    position:
      x: 0
      'y': 0
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
elements:
  - type: custom:frigate-card-conditional
    conditions:
      view:
        - live
      camera:
        - camera.rua
      media_loaded: false
    elements:
      - type: custom:frigate-card-ptz
        orientation: vertical
        service: onvif.ptz
        style:
          transform: none
          right: 5%
          top: 45%
        data_up:
          entity_id: camera.rua_onvif
          tilt: UP
          move_mode: ContinuousMove
          speed: 0.05
          continuous_duration: 0.05
        data_down:
          entity_id: camera.rua_onvif
          tilt: DOWN
          move_mode: ContinuousMove
          speed: 0.05
          continuous_duration: 0.05
        data_left:
          entity_id: camera.rua_onvif
          pan: LEFT
          move_mode: ContinuousMove
          speed: 0.05
          continuous_duration: 0.05
        data_right:
          entity_id: camera.rua_onvif
          pan: RIGHT
          move_mode: ContinuousMove
          speed: 0.05
          continuous_duration: 0.05
  - type: custom:frigate-card-conditional
    conditions:
      view:
        - live
      camera:
        - camera.rua
    elements:
      - type: custom:frigate-card-menu-submenu-select
        entity: select.camera_da_rua_night_vision
        options:
          '0':
            icon: mdi:theme-light-dark
          '1':
            icon: mdi:weather-sunny
          '2':
            icon: mdi:weather-night
cameras:
  - camera_entity: camera.video_porteiro
    live_provider: webrtc-card
    webrtc_card:
      url: video_porteiro
      muted: true
      ui: true
      mode: webrtc
      style: |
        video {aspect-ratio: 16/9; object-fit: cover; object-position: left top;}
        .mode {display: none}
        .fullscreen {display: none}
    dependencies:
      cameras:
        - video_porteiro_hd
  - camera_entity: camera.rua
    live_provider: webrtc-card
    webrtc_card:
      url: rua
      muted: true
      ui: true
      mode: webrtc
      style: |
        video {aspect-ratio: 16/9; object-fit: cover; object-position: left top;}
        .mode {display: none}
        .fullscreen {display: none}
    dependencies:
      cameras:
        - rua_hd
  - camera_entity: camera.morro
    live_provider: webrtc-card
    webrtc_card:
      url: morro
      muted: true
      ui: true
      mode: webrtc
      style: |
        video {aspect-ratio: 16/9; object-fit: cover; object-position: left top;}
        .mode {display: none}
        .fullscreen {display: none}
    dependencies:
      cameras:
        - morro_hd
  - camera_entity: camera.portao
    live_provider: webrtc-card
    webrtc_card:
      url: portao
      muted: true
      ui: true
      mode: webrtc
      style: |
        video {aspect-ratio: 16/9; object-fit: cover; object-position: left top;}
        .mode {display: none}
        .fullscreen {display: none}
  - camera_entity: camera.video_porteiro
    live_provider: webrtc-card
    title: Vídeo Porteiro (HD)
    id: video_porteiro_hd
    webrtc_card:
      url: video_porteiro_hd
      muted: true
      ui: true
      mode: webrtc
      style: |
        video {aspect-ratio: 16/9; object-fit: cover; object-position: left top;}
        .mode {display: none}
        .fullscreen {display: none}
    hide: true
  - camera_entity: camera.rua
    live_provider: webrtc-card
    title: Rua (HD)
    id: rua_hd
    webrtc_card:
      url: rua_hd
      muted: true
      ui: true
      mode: webrtc
      style: |
        video {aspect-ratio: 16/9; object-fit: cover; object-position: left top;}
        .mode {display: none}
        .fullscreen {display: none}
    hide: true
  - camera_entity: camera.morro
    live_provider: webrtc-card
    title: Morro (HD)
    id: morro_hd
    webrtc_card:
      url: morro_hd
      muted: true
      ui: true
      mode: webrtc
      style: |
        video {aspect-ratio: 16/9; object-fit: cover; object-position: left top;}
        .mode {display: none}
        .fullscreen {display: none}
    hide: true
  - camera_entity: camera.portao
    live_provider: webrtc-card
    title: Portão (HD)
    id: portao_hd
    webrtc_card:
      url: portao_hd
      muted: true
      ui: true
      mode: webrtc
      style: |
        video {aspect-ratio: 16/9; object-fit: cover; object-position: left top;}
        .mode {display: none}
        .fullscreen {display: none}
    hide: true
    dependencies:
      cameras:
        - camera.portao
image:
  mode: camera
performance:
  profile: low
  features:
    animated_progress_indicator: false
  style:
    box_shadow: false
    border_radius: false
media_viewer:
  auto_play: all
  auto_unmute: all
```

Also, I'm a bit unsure on how I should migrate my "override" for full screen as well with the new approach.

**Comment by felipecrs** [comment]
That is just one of my 4 cards. I have 2 others with a similar amount of cameras, and another one that includes all the cameras I have (which sums up to 15 counting the substreams).

**Comment by felipecrs** [comment]
> Random PS: Performance profile low should automatically set the other items you list under performance to the values you are specifying.

Ops, thank you. In fact, I have to spend some time to cleanup my config (removing the default settings).

**Comment by felipecrs** [comment]
By the way I have noticed another problem with this change.

Now, I can't override the webrtc_card style if the card is in full screen. For example, I like to use "cover" style when my cards are in the dashboard, but when in full screen I like to use the "contain" so that when viewing the stream in mobile vertically it will not fill the scream with the camera.

My suggestion to tackle this and also the concern about code duplication would be to have some:

```yaml
cameras_global:
  live_provider: go2rtc
  go2rtc:
    modes:
      - webrtc
```

Where I could set anything in `cameras_global` and that would be used by each camera, although I would still be able to override per camera if needed.

**Comment by dermotduffy** [comment]
> Now, I can't override the webrtc_card style if the card is in full screen. For example, I like to use "cover" style when my cards are in the dashboard, but when in full screen I like to use the "contain" so that when viewing the stream in mobile vertically it will not fill the scream with the camera.

Yes, this is an exact example of the lost override functionality. 

I don't really want to just revert this, as the old code was broken too and had subtle bugs. Implementation wise this is not as easy as it seems, since cameras are treated differently than the rest of the config -- they are loaded on card init, but then cannot be easily overridden since they're already loaded. It will take a bit of work to get this into a good state. I'll open a new issue.

**Pull request merged**
