### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by Redblockmasteur**
Add french translation

Preview the messages on https://inlang.com/github.com/Redblockmasteur/frigate-hass-card .

### CODE REVIEW

**Comment by dermotduffy** [comment]
Thank you @Redblockmasteur ! Note that the strings on the `dev` branch are what I'd suggest we translate -- this is what I linked to on the other thread, but that's subtle I know! If it's not easy for you to move between one and the other (I seem to recall `inlang` doesn't support branches?), then I am (very) happy to accept this and attempt to migrate to the new `dev` branch strings manually -- but there'll be some gaps if I do so.

**Comment by Redblockmasteur** [comment]
So if i understand correctly if our merge there will be gaps. However after you merge could I just re-do the missing strings ?
Its not that `inlang` does not support branches, but when I cloned the repo it only cloned the `main`.
I'm not an expert but i know that commits to main are suboptimal to say the least. But to be honest i did not realized that i was making a pool request to main before you pointed out.
If that works better for you i could make a branch `fr-translation` into my repo and make an other pool request ?
image
image

**Comment by dermotduffy** [comment]
> So if i understand correctly if you merge there will be gaps. However after you merge could I just re-do the missing strings ?

Sure! I can't comment on `inlang` support, but you could certain just create a new PR on the json file and manually add in the missing strings. If you wanted to do that, here's what I'd suggest:

 - We merge this PR on `main`.
 - I cherrypick it across to `dev` and add all the missing keys as empty strings.
 - You could prepare a manual PR to fills in those empty strings.

Is this what you'd like to do?

**Comment by Redblockmasteur** [comment]
Sorry for the late reply. Yes, please proceed with the plan we discussed earlier.

**Comment by dermotduffy** [comment]
@Redblockmasteur Thank you so much for the `fr` translations. I needed to do quite a bit of surgery to change the branch  on this, and so many other things have changed between the branches, that I just copied the translations out of this PR and into a fresh one on the  dev branch, in https://github.com/dermotduffy/frigate-hass-card/pull/1417 .

If you wanted to fill in the remaining blanks for the `fr` translations, I'd really appreciate it: https://github.com/dermotduffy/frigate-hass-card/blob/dev/src/localize/languages/fr.json

But either way, thank you so much for the contribution!

**Pull request closed without merging**
