### PR TITLE
Add out-of-the-box Frigate PTZ support

### LINKED ISSUE #1163: Transparently call Frigate PTZ via integration
it appears from the latest dev builds that frigate 0.13 will support PTZ natively via ONVIF. it would be nice to be able to configure this only within Frigate itself and have this functionality inherited by the frigate-hass-card instead of needing to add webrtc card into the mix. 

it seems as though PTZ functionality has been available in frigate-hass-card since before the PR for ptz control in the frigate repo.

(please correct me if my understanding is incorrect)

### PR DESCRIPTION
**Pull request by dermotduffy**
* Closes #1163 
* Breaks existing PTZ controls by moving `custom:frigate-card-ptz` element into a normal part of the configuration (under `live`) -- auto-upgrade offered that should cover most (but not all) cases.
* Requires at least integration [v5.0.0-beta.3](https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v5.0.0-beta.3).

### CODE REVIEW

**Comment by Sidonai-1** [comment]
Hi!, I'm trying to use the card built-in controls without having to write a long yaml, but the options don't appear in the menu, is there some reason this could be? With the yaml it works, and it works correctly in frigate.

Thanks.

**Comment by dermotduffy** [comment]
@Sidonai-1 The code is not yet in an official release, so you'd need to be using the `dev` branch for this to work out of the box. See [here](https://card.camera/#/advanced-installation?id=unreleased-versions) if you'd like to install your own from the `dev` branch, otherwise wait for an official release.

**Comment by Sidonai-1** [comment]
I see, that makes sense. I mistakenly thought it was on the main branch already from reading the commits.

Thank you very much!

**Comment by awh018** [comment]
I've installed the latest dev version 6.0.0-beta 5 and I cannot seem to figure out the built in PTZ. Do I need to modify the YAML, or should I be able to configure everything within the config? Thanks for your awesome work on this.

**Comment by dermotduffy** [comment]
If you visit the Frigate UI, can you control the camera from there? If yes, then zero extra configuration should be necessary on the card for PTZ. For example, here's a test config I just make that shows PTZ controls on a Frigate camera:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
    live_provider: go2rtc
```

If your camera does not have PTZ support in Frigate, but is a PTZ camera that is controllable via Home Assistant, you could manually configure PTZ. See docs: https://card.camera/#/examples?id=ptz-control

**Comment by awh018** [comment]
Thanks for the response. Yes the camera is perfectly controllable in Frigate. Using your example does get the PTZ controls to show, but they don't move the camera at all. I had it working before with ONVIF but would prefer to use the built in PTZ.

**Comment by dermotduffy** [comment]
Please file a new issue and be sure to include the diagnostics (hold down the Frigate button for a few seconds and paste the result). Thanks!

**Pull request merged**
