### PR TITLE
Show still images during live camera load

### LINKED ISSUE #762: Support using camera image as live background during loading

### PR DESCRIPTION
**Pull request by dermotduffy**
* Closes #762

### CODE REVIEW

**Comment by dermotduffy** [comment]
@felipecrs This one is probably also relevant to your interests. This worked out really well in my setup (surprisingly so for the effort invested) -- it gives the appearance of instantaneous camera stream loads by using still images from the camera until the video player reports the stream is loaded. Let me know if it works, or doesn't, for you also ...

**Comment by felipecrs** [comment]
Wow, I was shocked on how well this works! Do you think it's possible to extend this functionality to the JSMPEG live view provider too?

**Comment by dermotduffy** [comment]
> Wow, I was shocked on how well this works!

Me too honestly...

> Do you think it's possible to extend this functionality to the JSMPEG live view provider too?

Hmm. It should already work for JSMPEG live provider also (at least it does for me)...

**Comment by felipecrs** [comment]
https://user-images.githubusercontent.com/29582865/183561484-21960dd8-ca87-41f2-a836-cbf6e278c36f.mp4

Hm... so it only starts to be effective after the card is already loaded, is that right? I think this is why I thought it was not working. If so, it's working.

Do you think it's possible to also extend the functionality to the first load (like when refreshing the page)? I guess HA camera entities provides still image sources that could be used for that.

**Comment by dermotduffy** [comment]
> Hm... so it only starts to be effective after the card is already loaded, is that right? I think this is why I thought it was not working. If so, it's working.

Oh. Hmm. I don't see why it shouldn't work from the very start, let me look into that.

**Pull request merged**
