### PR TITLE
Bump prettier to v3 and format all files

### PR DESCRIPTION
**Pull request by felipecrs**
Here are the only things I changed beyond formatting all files with prettier:

1. Updated prettier to v3, and eslint-config-prettier to its latest version
2. Removed eslint-plugin-prettier as it was not being used, and personally I find it redundant
3. Enabled eslint-config-prettier in eslint configuration, which was not being enabled before (probably by mistake)
4. Added the format and format-check scripts to the package.json file
5. Added lint and format-check to the build GitHub Actions workflow
6. Converted the prettier configuration file to ESM with typescript checking
7. Added docs/js to .prettierignore
8. Changed snippets in docs to a format that Prettier likes more, like `[...]` to `# [...]`
9. Also fixed a few inconsistencies in the docs snippets like the [overrides.md](https://github.com/dermotduffy/frigate-hass-card/commit/91b0909614b5a29af04dd6542a4b135e2ae1b5be#diff-5fb3c02c37ecdbe0a4938ff555db60e138bafa659d39d41649d57f81e54f1bca)

### CODE REVIEW

**Comment by dermotduffy** [comment]
Nice! Quick reaction (will review properly later): The `docs/js` folder should be ignored from reformatting, since it is just static fetches of other bundles for local serving.

**Comment by felipecrs** [comment]
Oh, perfect. Let me exclude it then.

**Comment by felipecrs** [comment]
BTW, I noticed you seem to like `*` for unordered lists in markdown more than `-`, but unfortunately this is not an option in Prettier. They seem to have some reasoning behind it, which I didn't go too deep to understand.

**Comment by felipecrs** [comment]
By the way I advise you don't spend much time reviewing all these changes. Except by what I listed at the PR description, everything was made by Prettier.

Speaking of which, I noticed some "regressions" in the docs, which I fixed in https://github.com/dermotduffy/frigate-hass-card/pull/1472/commits/91b0909614b5a29af04dd6542a4b135e2ae1b5be.

**Comment by dermotduffy** [comment]
Thanks @felipecrs !

**Pull request merged**
