### PR TITLE
Fix devcontainer for latest Frigate and Home Assistant

### PR DESCRIPTION
**Pull request by felipecrs**
- Depends on https://github.com/blakeblackshear/frigate-hass-integration/pull/720

Also:

- Make vscode automatically run `yarn start` on startup

### CODE REVIEW

**Comment by felipecrs** [comment]
@dermotduffy, it's working like a charm now (again). We just need to wait for the PR at the integration side to be merged.

**Comment by dermotduffy** [comment]
> @dermotduffy, it's working like a charm now (again). We just need to wait for the PR at the integration side to be merged.

Done!

**Comment by felipecrs** [comment]
Thank you, this one is ready to merge now too.

**Comment by dermotduffy** [comment]
Thanks @felipecrs !

**Pull request merged**
